USE student_management_db;

ALTER TABLE users
  DROP INDEX email_2,
  DROP INDEX email_3,
  DROP INDEX email_4,
  DROP INDEX email_5,
  DROP INDEX email_6,
  DROP INDEX email_7,
  DROP INDEX email_8,
  DROP INDEX email_9,
  DROP INDEX email_10,
  DROP INDEX email_11,
  DROP INDEX email_12,
  DROP INDEX email_13,
  DROP INDEX email_14,
  DROP INDEX email_15,
  DROP INDEX email_16,
  DROP INDEX email_17,
  DROP INDEX email_18,
  DROP INDEX email_19,
  DROP INDEX email_20,
  DROP INDEX email_21,
  DROP INDEX email_22,
  DROP INDEX email_23;

ALTER TABLE students
  DROP INDEX studentCode_2,
  DROP INDEX studentCode_3,
  DROP INDEX studentCode_4,
  DROP INDEX studentCode_5,
  DROP INDEX studentCode_6,
  DROP INDEX studentCode_7,
  DROP INDEX studentCode_8,
  DROP INDEX studentCode_9,
  DROP INDEX studentCode_10,
  DROP INDEX studentCode_11,
  DROP INDEX studentCode_12,
  DROP INDEX studentCode_13,
  DROP INDEX studentCode_14,
  DROP INDEX studentCode_15,
  DROP INDEX studentCode_16,
  DROP INDEX studentCode_17,
  DROP INDEX studentCode_18,
  DROP INDEX studentCode_19,
  DROP INDEX studentCode_20,
  DROP INDEX studentCode_21;

ALTER TABLE students
  DROP FOREIGN KEY students_ibfk_2,
  DROP FOREIGN KEY students_ibfk_3,
  DROP FOREIGN KEY students_ibfk_4,
  DROP FOREIGN KEY students_ibfk_5,
  DROP FOREIGN KEY students_ibfk_6,
  DROP FOREIGN KEY students_ibfk_7,
  DROP FOREIGN KEY students_ibfk_8,
  DROP FOREIGN KEY students_ibfk_9,
  DROP FOREIGN KEY students_ibfk_10,
  DROP FOREIGN KEY students_ibfk_11,
  DROP FOREIGN KEY students_ibfk_12,
  DROP FOREIGN KEY students_ibfk_13,
  DROP FOREIGN KEY students_ibfk_14,
  DROP FOREIGN KEY students_ibfk_15,
  DROP FOREIGN KEY students_ibfk_16,
  DROP FOREIGN KEY students_ibfk_17,
  DROP FOREIGN KEY students_ibfk_18,
  DROP FOREIGN KEY students_ibfk_19,
  DROP FOREIGN KEY students_ibfk_20,
  DROP FOREIGN KEY students_ibfk_21,
  DROP FOREIGN KEY students_ibfk_22;

ALTER TABLE attendances
  DROP FOREIGN KEY attendances_ibfk_2,
  DROP FOREIGN KEY attendances_ibfk_3,
  DROP FOREIGN KEY attendances_ibfk_4,
  DROP FOREIGN KEY attendances_ibfk_5,
  DROP FOREIGN KEY attendances_ibfk_6,
  DROP FOREIGN KEY attendances_ibfk_7,
  DROP FOREIGN KEY attendances_ibfk_8,
  DROP FOREIGN KEY attendances_ibfk_9,
  DROP FOREIGN KEY attendances_ibfk_10,
  DROP FOREIGN KEY attendances_ibfk_11,
  DROP FOREIGN KEY attendances_ibfk_12,
  DROP FOREIGN KEY attendances_ibfk_13,
  DROP FOREIGN KEY attendances_ibfk_14,
  DROP FOREIGN KEY attendances_ibfk_15,
  DROP FOREIGN KEY attendances_ibfk_16,
  DROP FOREIGN KEY attendances_ibfk_17,
  DROP FOREIGN KEY attendances_ibfk_18,
  DROP FOREIGN KEY attendances_ibfk_19,
  DROP FOREIGN KEY attendances_ibfk_20,
  DROP FOREIGN KEY attendances_ibfk_21;

ALTER TABLE grades
  DROP FOREIGN KEY grades_ibfk_2,
  DROP FOREIGN KEY grades_ibfk_3,
  DROP FOREIGN KEY grades_ibfk_4,
  DROP FOREIGN KEY grades_ibfk_5,
  DROP FOREIGN KEY grades_ibfk_6,
  DROP FOREIGN KEY grades_ibfk_7,
  DROP FOREIGN KEY grades_ibfk_8,
  DROP FOREIGN KEY grades_ibfk_9,
  DROP FOREIGN KEY grades_ibfk_10,
  DROP FOREIGN KEY grades_ibfk_11,
  DROP FOREIGN KEY grades_ibfk_12,
  DROP FOREIGN KEY grades_ibfk_13,
  DROP FOREIGN KEY grades_ibfk_14,
  DROP FOREIGN KEY grades_ibfk_15,
  DROP FOREIGN KEY grades_ibfk_16,
  DROP FOREIGN KEY grades_ibfk_17,
  DROP FOREIGN KEY grades_ibfk_18,
  DROP FOREIGN KEY grades_ibfk_19,
  DROP FOREIGN KEY grades_ibfk_20,
  DROP FOREIGN KEY grades_ibfk_21;

ALTER TABLE predictions
  DROP FOREIGN KEY predictions_ibfk_2,
  DROP FOREIGN KEY predictions_ibfk_3,
  DROP FOREIGN KEY predictions_ibfk_4,
  DROP FOREIGN KEY predictions_ibfk_5,
  DROP FOREIGN KEY predictions_ibfk_6,
  DROP FOREIGN KEY predictions_ibfk_7,
  DROP FOREIGN KEY predictions_ibfk_8,
  DROP FOREIGN KEY predictions_ibfk_9,
  DROP FOREIGN KEY predictions_ibfk_10,
  DROP FOREIGN KEY predictions_ibfk_11,
  DROP FOREIGN KEY predictions_ibfk_12,
  DROP FOREIGN KEY predictions_ibfk_13,
  DROP FOREIGN KEY predictions_ibfk_14,
  DROP FOREIGN KEY predictions_ibfk_15,
  DROP FOREIGN KEY predictions_ibfk_16,
  DROP FOREIGN KEY predictions_ibfk_17,
  DROP FOREIGN KEY predictions_ibfk_18,
  DROP FOREIGN KEY predictions_ibfk_19,
  DROP FOREIGN KEY predictions_ibfk_20;
